### ISSUE TITLE
Ask for confirmation before deploying(any env) and show the packages that will be deployed.

### ISSUE THREAD

**Issue by ev-agelos** [SoftwearDevelopment/spynl#6]
Sometimes when deploying (to any environment) some packages might be missing from the environment(forgot to install them) and build gets triggered.
It would be nice to show a question like:
```
The following plugins will be included in the build:
Plugin A
Plugin B
...
Procced with the build Y/N:
```
That way you can see clearly what plugins will be installed(in case you miss some) and have a chance to cancel the build.

**Comment by o-m-n-i** [comment]
This was already solved.
