### ISSUE TITLE
Spynl ops build --task fails on Jenkins when using dev and production

### ISSUE THREAD

**Issue by o-m-n-i** [SoftwearDevelopment/spynl#8]
If you use `spynl ops.start_build --task=latest,dev,production`, Jenkins will fail with the following message
![screenshot from 2017-03-01 11-40-41](https://cloud.githubusercontent.com/assets/3542312/23456563/385a1ff2-fe74-11e6-89eb-46514acb95e3.png)

**Comment by Kareeeeem** [comment]
I'm not sure if this is still an issue for you.

But it seems this is intended behavior. So you can't run build dev and production at the same time. Production always has to be  built seperately.

I will adress the error handling here though.

**Comment by o-m-n-i** [comment]
I will close this issue now as it's been addressed.
